USE master;
GO

IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'BigData_Group24')
BEGIN
    ALTER DATABASE BigData_Group24 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE BigData_Group24;
END
GO

CREATE DATABASE BigData_Group24;
GO